# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\procedure\groundstation\English\groundstation.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1447, 927)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(100, 40, 441, 341))
        self.groupBox.setStyleSheet(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 310, 61, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(380, 310, 61, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(160, 310, 61, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(230, 310, 71, 23))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 310, 21, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(40, 310, 113, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 401, 281))
        self.label_2.setStyleSheet(_fromUtf8("border-image:url(D:/procedure/groundstation/huiyi1.png)"))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(320, 20, 101, 91))
        self.label_3.setStyleSheet(_fromUtf8("border-image:url(D:/procedure/groundstation/huiyi2.png)"))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(540, 40, 441, 341))
        self.groupBox_2.setStyleSheet(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 401, 281))
        self.label_4.setStyleSheet(_fromUtf8("border-image:url(D:/procedure/groundstation/hangpai1.png)"))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(970, 40, 331, 341))
        self.groupBox_3.setStyleSheet(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 311, 281))
        self.label_5.setStyleSheet(_fromUtf8("border-image:url(D:/procedure/groundstation/huwai1.png)"))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 310, 61, 23))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_7.setGeometry(QtCore.QRect(90, 310, 81, 23))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_8.setGeometry(QtCore.QRect(180, 310, 61, 23))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_9.setGeometry(QtCore.QRect(260, 310, 71, 23))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(100, 380, 391, 291))
        self.groupBox_4.setStyleSheet(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 341, 231))
        self.label_6.setStyleSheet(_fromUtf8("border-image:url(D:/procedure/groundstation/cheding1.png)"))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_10.setGeometry(QtCore.QRect(100, 260, 81, 23))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pushButton_11 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_11.setGeometry(QtCore.QRect(30, 260, 61, 23))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.groupBox_6 = QtGui.QGroupBox(Dialog)
        self.groupBox_6.setGeometry(QtCore.QRect(490, 380, 461, 301))
        self.groupBox_6.setStyleSheet(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(60, 20, 341, 231))
        self.label_7.setStyleSheet(_fromUtf8("border-image:url(D:/procedure/groundstation/ditu1.png)"))
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.groupBox_5 = QtGui.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(950, 380, 361, 301))
        self.groupBox_5.setStyleSheet(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.pushButton_12 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_12.setGeometry(QtCore.QRect(50, 80, 61, 23))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_13 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_13.setGeometry(QtCore.QRect(50, 160, 61, 23))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.pushButton_14 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_14.setGeometry(QtCore.QRect(0, 120, 61, 23))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.pushButton_15 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_15.setGeometry(QtCore.QRect(110, 120, 61, 23))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.pushButton_16 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_16.setGeometry(QtCore.QRect(240, 160, 61, 23))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.pushButton_17 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_17.setGeometry(QtCore.QRect(190, 120, 61, 23))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.pushButton_18 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_18.setGeometry(QtCore.QRect(300, 120, 61, 23))
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.pushButton_19 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_19.setGeometry(QtCore.QRect(240, 80, 61, 23))
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(20, 270, 151, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 270, 41, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.pushButton_20 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_20.setGeometry(QtCore.QRect(110, 230, 61, 23))
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.pushButton_21 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_21.setGeometry(QtCore.QRect(20, 230, 61, 23))
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.pushButton_22 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_22.setGeometry(QtCore.QRect(290, 230, 61, 23))
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.pushButton_23 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_23.setGeometry(QtCore.QRect(200, 230, 61, 23))
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.groupBox_7 = QtGui.QGroupBox(Dialog)
        self.groupBox_7.setGeometry(QtCore.QRect(100, 670, 391, 231))
        self.groupBox_7.setStyleSheet(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.pushButton_24 = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_24.setGeometry(QtCore.QRect(110, 40, 61, 23))
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.pushButton_25 = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_25.setGeometry(QtCore.QRect(20, 40, 51, 23))
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.label_9 = QtGui.QLabel(self.groupBox_7)
        self.label_9.setGeometry(QtCore.QRect(190, 40, 81, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_3.setGeometry(QtCore.QRect(270, 40, 51, 20))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.pushButton_26 = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_26.setGeometry(QtCore.QRect(20, 100, 101, 23))
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.pushButton_27 = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_27.setGeometry(QtCore.QRect(20, 150, 101, 23))
        self.pushButton_27.setObjectName(_fromUtf8("pushButton_27"))
        self.groupBox_8 = QtGui.QGroupBox(Dialog)
        self.groupBox_8.setGeometry(QtCore.QRect(490, 680, 821, 221))
        self.groupBox_8.setStyleSheet(_fromUtf8(""))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.label_10 = QtGui.QLabel(self.groupBox_8)
        self.label_10.setGeometry(QtCore.QRect(30, 40, 91, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 40, 61, 20))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.label_11 = QtGui.QLabel(self.groupBox_8)
        self.label_11.setGeometry(QtCore.QRect(30, 120, 81, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_5.setGeometry(QtCore.QRect(130, 120, 51, 20))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.label_12 = QtGui.QLabel(self.groupBox_8)
        self.label_12.setGeometry(QtCore.QRect(30, 80, 91, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_6.setGeometry(QtCore.QRect(130, 80, 51, 20))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.label_13 = QtGui.QLabel(self.groupBox_8)
        self.label_13.setGeometry(QtCore.QRect(30, 160, 81, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lineEdit_7 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_7.setGeometry(QtCore.QRect(130, 160, 51, 20))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.label_14 = QtGui.QLabel(self.groupBox_8)
        self.label_14.setGeometry(QtCore.QRect(330, 120, 161, 20))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lineEdit_8 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_8.setGeometry(QtCore.QRect(490, 120, 51, 20))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.label_15 = QtGui.QLabel(self.groupBox_8)
        self.label_15.setGeometry(QtCore.QRect(190, 160, 81, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lineEdit_9 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_9.setGeometry(QtCore.QRect(270, 160, 51, 20))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.label_16 = QtGui.QLabel(self.groupBox_8)
        self.label_16.setGeometry(QtCore.QRect(190, 80, 81, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.lineEdit_10 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_10.setGeometry(QtCore.QRect(270, 80, 51, 20))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.label_17 = QtGui.QLabel(self.groupBox_8)
        self.label_17.setGeometry(QtCore.QRect(190, 120, 81, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.lineEdit_11 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_11.setGeometry(QtCore.QRect(270, 120, 51, 20))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.label_18 = QtGui.QLabel(self.groupBox_8)
        self.label_18.setGeometry(QtCore.QRect(330, 40, 121, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.lineEdit_12 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_12.setGeometry(QtCore.QRect(490, 40, 51, 20))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.label_19 = QtGui.QLabel(self.groupBox_8)
        self.label_19.setGeometry(QtCore.QRect(330, 80, 111, 20))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.lineEdit_13 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_13.setGeometry(QtCore.QRect(490, 80, 51, 20))
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.label_20 = QtGui.QLabel(self.groupBox_8)
        self.label_20.setGeometry(QtCore.QRect(190, 40, 81, 20))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.lineEdit_14 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_14.setGeometry(QtCore.QRect(270, 40, 51, 20))
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.label_21 = QtGui.QLabel(self.groupBox_8)
        self.label_21.setGeometry(QtCore.QRect(550, 10, 121, 20))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.lineEdit_15 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_15.setGeometry(QtCore.QRect(550, 30, 261, 161))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox.setTitle(_translate("Dialog", "Meeting", None))
        self.pushButton_2.setText(_translate("Dialog", "Record", None))
        self.pushButton_3.setText(_translate("Dialog", "Stop", None))
        self.pushButton_4.setText(_translate("Dialog", "Connect", None))
        self.pushButton_5.setText(_translate("Dialog", "Disconnect", None))
        self.label.setText(_translate("Dialog", "IP：", None))
        self.lineEdit.setText(_translate("Dialog", "192.168.1.101", None))
        self.groupBox_2.setTitle(_translate("Dialog", "UAV Cameras", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Single pawns", None))
        self.pushButton_6.setText(_translate("Dialog", "Connect", None))
        self.pushButton_7.setText(_translate("Dialog", "Disconnect", None))
        self.pushButton_8.setText(_translate("Dialog", "Sound on", None))
        self.pushButton_9.setText(_translate("Dialog", "Sound off", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Outside Cameras", None))
        self.pushButton_10.setText(_translate("Dialog", "disconnect", None))
        self.pushButton_11.setText(_translate("Dialog", "connect", None))
        self.groupBox_6.setTitle(_translate("Dialog", "Local Maps", None))
        self.groupBox_5.setTitle(_translate("Dialog", "UAV Control", None))
        self.pushButton_12.setText(_translate("Dialog", "Up", None))
        self.pushButton_13.setText(_translate("Dialog", "Down", None))
        self.pushButton_14.setText(_translate("Dialog", "LR", None))
        self.pushButton_15.setText(_translate("Dialog", "RR", None))
        self.pushButton_16.setText(_translate("Dialog", "Back", None))
        self.pushButton_17.setText(_translate("Dialog", "Left", None))
        self.pushButton_18.setText(_translate("Dialog", "Right", None))
        self.pushButton_19.setText(_translate("Dialog", "Front", None))
        self.label_8.setText(_translate("Dialog", "Default take-off height：", None))
        self.lineEdit_2.setText(_translate("Dialog", "50", None))
        self.pushButton_20.setText(_translate("Dialog", "Fly", None))
        self.pushButton_21.setText(_translate("Dialog", "Unlock", None))
        self.pushButton_22.setText(_translate("Dialog", "Lock", None))
        self.pushButton_23.setText(_translate("Dialog", "Land", None))
        self.groupBox_7.setTitle(_translate("Dialog", "Rescue and Air space dialogue ", None))
        self.pushButton_24.setText(_translate("Dialog", "Horn off", None))
        self.pushButton_25.setText(_translate("Dialog", "Horn on", None))
        self.label_9.setText(_translate("Dialog", "Volume db:", None))
        self.lineEdit_3.setText(_translate("Dialog", "60", None))
        self.pushButton_26.setText(_translate("Dialog", "Open Parabolic", None))
        self.pushButton_27.setText(_translate("Dialog", "Closs Parabolic", None))
        self.groupBox_8.setTitle(_translate("Dialog", "Auxiliary decision ", None))
        self.label_10.setText(_translate("Dialog", "Identification:", None))
        self.lineEdit_4.setText(_translate("Dialog", "landslide", None))
        self.label_11.setText(_translate("Dialog", "Longitude:", None))
        self.lineEdit_5.setText(_translate("Dialog", "97.5", None))
        self.label_12.setText(_translate("Dialog", "Water content:", None))
        self.lineEdit_6.setText(_translate("Dialog", "60%", None))
        self.label_13.setText(_translate("Dialog", "Latitudes:", None))
        self.lineEdit_7.setText(_translate("Dialog", "31.7", None))
        self.label_14.setText(_translate("Dialog", "Number of GPS satellites:", None))
        self.lineEdit_8.setText(_translate("Dialog", "8", None))
        self.label_15.setText(_translate("Dialog", "Electricity:", None))
        self.lineEdit_9.setText(_translate("Dialog", "60%", None))
        self.label_16.setText(_translate("Dialog", "Height:", None))
        self.lineEdit_10.setText(_translate("Dialog", "300", None))
        self.label_17.setText(_translate("Dialog", "Distance:", None))
        self.lineEdit_11.setText(_translate("Dialog", "1200", None))
        self.label_18.setText(_translate("Dialog", "Horizontal velocity: ", None))
        self.lineEdit_12.setText(_translate("Dialog", "2.3", None))
        self.label_19.setText(_translate("Dialog", "Vertical velocity:", None))
        self.lineEdit_13.setText(_translate("Dialog", "1.3", None))
        self.label_20.setText(_translate("Dialog", "Lock:", None))
        self.lineEdit_14.setText(_translate("Dialog", "No", None))
        self.label_21.setText(_translate("Dialog", "Auxiliary decision:", None))
        self.lineEdit_15.setText(_translate("Dialog", "It is recommended to go to the Region...", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

