# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\procedure\groundstation\gs\groundstation.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1447, 927)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(100, 40, 441, 341))
        self.groupBox.setStyleSheet(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 310, 61, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(370, 310, 61, 23))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(160, 310, 61, 23))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(230, 310, 61, 23))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 310, 21, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 401, 281))
        self.label_2.setStyleSheet(_fromUtf8("border-image:url(D:/procedure/groundstation/huiyi1.png)"))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(320, 20, 101, 91))
        self.label_3.setStyleSheet(_fromUtf8("border-image:url(D:/procedure/groundstation/huiyi2.png)"))
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit_29 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_29.setGeometry(QtCore.QRect(40, 310, 111, 20))
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(540, 40, 441, 341))
        self.groupBox_2.setStyleSheet(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 401, 281))
        self.label_4.setStyleSheet(_fromUtf8("border-image:url(D:/procedure/groundstation/hangpai1.png)"))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(970, 40, 331, 341))
        self.groupBox_3.setStyleSheet(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 311, 281))
        self.label_5.setStyleSheet(_fromUtf8("border-image:url(D:/procedure/groundstation/huwai1.png)"))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 310, 61, 23))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_7.setGeometry(QtCore.QRect(90, 310, 61, 23))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_8.setGeometry(QtCore.QRect(190, 310, 61, 23))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_9.setGeometry(QtCore.QRect(260, 310, 61, 23))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(100, 380, 391, 291))
        self.groupBox_4.setStyleSheet(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 341, 231))
        self.label_6.setStyleSheet(_fromUtf8(""))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_10.setGeometry(QtCore.QRect(100, 260, 61, 23))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pushButton_11 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_11.setGeometry(QtCore.QRect(30, 260, 61, 23))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.groupBox_6 = QtGui.QGroupBox(Dialog)
        self.groupBox_6.setGeometry(QtCore.QRect(490, 380, 461, 301))
        self.groupBox_6.setStyleSheet(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(60, 20, 341, 231))
        self.label_7.setStyleSheet(_fromUtf8("border-image:url(D:/procedure/groundstation/ditu1.png)"))
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.groupBox_5 = QtGui.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(950, 380, 361, 301))
        self.groupBox_5.setStyleSheet(_fromUtf8("background:rgb(189, 232, 255)"))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.pushButton_12 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_12.setGeometry(QtCore.QRect(50, 80, 61, 23))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_13 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_13.setGeometry(QtCore.QRect(50, 160, 61, 23))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.pushButton_14 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_14.setGeometry(QtCore.QRect(0, 120, 61, 23))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.pushButton_15 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_15.setGeometry(QtCore.QRect(110, 120, 61, 23))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.pushButton_16 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_16.setGeometry(QtCore.QRect(240, 160, 61, 23))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.pushButton_17 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_17.setGeometry(QtCore.QRect(190, 120, 61, 23))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.pushButton_18 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_18.setGeometry(QtCore.QRect(300, 120, 61, 23))
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.pushButton_19 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_19.setGeometry(QtCore.QRect(240, 80, 61, 23))
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(20, 270, 81, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 270, 41, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.pushButton_20 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_20.setGeometry(QtCore.QRect(110, 230, 61, 23))
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.pushButton_21 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_21.setGeometry(QtCore.QRect(20, 230, 61, 23))
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.pushButton_22 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_22.setGeometry(QtCore.QRect(290, 230, 61, 23))
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.pushButton_23 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_23.setGeometry(QtCore.QRect(200, 230, 61, 23))
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.groupBox_7 = QtGui.QGroupBox(Dialog)
        self.groupBox_7.setGeometry(QtCore.QRect(100, 670, 391, 231))
        self.groupBox_7.setStyleSheet(_fromUtf8(""))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.pushButton_24 = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_24.setGeometry(QtCore.QRect(110, 40, 61, 23))
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.pushButton_25 = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_25.setGeometry(QtCore.QRect(20, 40, 61, 23))
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.label_9 = QtGui.QLabel(self.groupBox_7)
        self.label_9.setGeometry(QtCore.QRect(190, 40, 81, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.pushButton_26 = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_26.setGeometry(QtCore.QRect(20, 100, 61, 23))
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.pushButton_27 = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_27.setGeometry(QtCore.QRect(110, 100, 61, 23))
        self.pushButton_27.setObjectName(_fromUtf8("pushButton_27"))
        self.lineEdit_16 = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_16.setGeometry(QtCore.QRect(260, 40, 51, 20))
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.groupBox_8 = QtGui.QGroupBox(Dialog)
        self.groupBox_8.setGeometry(QtCore.QRect(490, 680, 821, 221))
        self.groupBox_8.setStyleSheet(_fromUtf8(""))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.label_10 = QtGui.QLabel(self.groupBox_8)
        self.label_10.setGeometry(QtCore.QRect(30, 40, 81, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_8)
        self.label_11.setGeometry(QtCore.QRect(30, 120, 81, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox_8)
        self.label_12.setGeometry(QtCore.QRect(30, 80, 81, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_8)
        self.label_13.setGeometry(QtCore.QRect(30, 160, 81, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_8)
        self.label_14.setGeometry(QtCore.QRect(190, 40, 81, 20))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_8)
        self.label_15.setGeometry(QtCore.QRect(190, 160, 81, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.groupBox_8)
        self.label_16.setGeometry(QtCore.QRect(190, 80, 81, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.groupBox_8)
        self.label_17.setGeometry(QtCore.QRect(190, 120, 81, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.groupBox_8)
        self.label_18.setGeometry(QtCore.QRect(360, 120, 81, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.groupBox_8)
        self.label_19.setGeometry(QtCore.QRect(360, 40, 81, 20))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.groupBox_8)
        self.label_20.setGeometry(QtCore.QRect(360, 80, 81, 20))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.groupBox_8)
        self.label_21.setGeometry(QtCore.QRect(510, 40, 81, 20))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.pushButton_28 = QtGui.QPushButton(self.groupBox_8)
        self.pushButton_28.setGeometry(QtCore.QRect(360, 160, 61, 23))
        self.pushButton_28.setObjectName(_fromUtf8("pushButton_28"))
        self.lineEdit_17 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_17.setGeometry(QtCore.QRect(110, 40, 51, 20))
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.lineEdit_18 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_18.setGeometry(QtCore.QRect(110, 80, 51, 20))
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.lineEdit_19 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_19.setGeometry(QtCore.QRect(110, 120, 51, 20))
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.lineEdit_20 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_20.setGeometry(QtCore.QRect(110, 160, 51, 20))
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.lineEdit_21 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_21.setGeometry(QtCore.QRect(270, 40, 51, 20))
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.lineEdit_22 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_22.setGeometry(QtCore.QRect(270, 80, 51, 20))
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.lineEdit_23 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_23.setGeometry(QtCore.QRect(270, 120, 51, 20))
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.lineEdit_24 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_24.setGeometry(QtCore.QRect(270, 160, 51, 20))
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.lineEdit_25 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_25.setGeometry(QtCore.QRect(440, 40, 51, 20))
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.lineEdit_26 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_26.setGeometry(QtCore.QRect(440, 80, 51, 20))
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.lineEdit_27 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_27.setGeometry(QtCore.QRect(440, 120, 51, 20))
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.lineEdit_28 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_28.setGeometry(QtCore.QRect(590, 40, 221, 151))
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox.setTitle(_translate("Dialog", "会议内容", None))
        self.pushButton_2.setText(_translate("Dialog", "开始录像", None))
        self.pushButton_3.setText(_translate("Dialog", "停止录像", None))
        self.pushButton_4.setText(_translate("Dialog", "连接", None))
        self.pushButton_5.setText(_translate("Dialog", "断开", None))
        self.label.setText(_translate("Dialog", "IP：", None))
        self.lineEdit_29.setText(_translate("Dialog", "192.168.1.108", None))
        self.groupBox_2.setTitle(_translate("Dialog", "无人机增强显示", None))
        self.groupBox_3.setTitle(_translate("Dialog", "单兵", None))
        self.pushButton_6.setText(_translate("Dialog", "连接", None))
        self.pushButton_7.setText(_translate("Dialog", "断开", None))
        self.pushButton_8.setText(_translate("Dialog", "接收声音", None))
        self.pushButton_9.setText(_translate("Dialog", "关闭声音", None))
        self.groupBox_4.setTitle(_translate("Dialog", "车外摄像头", None))
        self.pushButton_10.setText(_translate("Dialog", "断开", None))
        self.pushButton_11.setText(_translate("Dialog", "连接", None))
        self.groupBox_6.setTitle(_translate("Dialog", "全局地图", None))
        self.groupBox_5.setTitle(_translate("Dialog", "无人机控制", None))
        self.pushButton_12.setText(_translate("Dialog", "上", None))
        self.pushButton_13.setText(_translate("Dialog", "下", None))
        self.pushButton_14.setText(_translate("Dialog", "左旋", None))
        self.pushButton_15.setText(_translate("Dialog", "右旋", None))
        self.pushButton_16.setText(_translate("Dialog", "后", None))
        self.pushButton_17.setText(_translate("Dialog", "左", None))
        self.pushButton_18.setText(_translate("Dialog", "右", None))
        self.pushButton_19.setText(_translate("Dialog", "前", None))
        self.label_8.setText(_translate("Dialog", "默认起飞高度：", None))
        self.lineEdit_2.setText(_translate("Dialog", "50", None))
        self.pushButton_20.setText(_translate("Dialog", "一键起飞", None))
        self.pushButton_21.setText(_translate("Dialog", "解锁", None))
        self.pushButton_22.setText(_translate("Dialog", "一键解锁", None))
        self.pushButton_23.setText(_translate("Dialog", "一键降落", None))
        self.groupBox_7.setTitle(_translate("Dialog", "救援及空地对话", None))
        self.pushButton_24.setText(_translate("Dialog", "关闭喇叭", None))
        self.pushButton_25.setText(_translate("Dialog", "开启喇叭", None))
        self.label_9.setText(_translate("Dialog", "音量大小db：", None))
        self.pushButton_26.setText(_translate("Dialog", "开启抛物", None))
        self.pushButton_27.setText(_translate("Dialog", "关闭抛物", None))
        self.lineEdit_16.setText(_translate("Dialog", "60", None))
        self.groupBox_8.setTitle(_translate("Dialog", "辅助决策", None))
        self.label_10.setText(_translate("Dialog", "识别情况：", None))
        self.label_11.setText(_translate("Dialog", "经度：", None))
        self.label_12.setText(_translate("Dialog", "水分含量：", None))
        self.label_13.setText(_translate("Dialog", "纬度：", None))
        self.label_14.setText(_translate("Dialog", "GPS卫星数目：", None))
        self.label_15.setText(_translate("Dialog", "电量：", None))
        self.label_16.setText(_translate("Dialog", "高度：", None))
        self.label_17.setText(_translate("Dialog", "距离：", None))
        self.label_18.setText(_translate("Dialog", "水平速度：", None))
        self.label_19.setText(_translate("Dialog", "竖直速度：", None))
        self.label_20.setText(_translate("Dialog", "锁定状态：", None))
        self.label_21.setText(_translate("Dialog", "决策与建议：", None))
        self.pushButton_28.setText(_translate("Dialog", "历史记录", None))
        self.lineEdit_17.setText(_translate("Dialog", "是", None))
        self.lineEdit_18.setText(_translate("Dialog", "60%", None))
        self.lineEdit_19.setText(_translate("Dialog", "119", None))
        self.lineEdit_20.setText(_translate("Dialog", "25", None))
        self.lineEdit_21.setText(_translate("Dialog", "7", None))
        self.lineEdit_22.setText(_translate("Dialog", "500", None))
        self.lineEdit_23.setText(_translate("Dialog", "2000", None))
        self.lineEdit_24.setText(_translate("Dialog", "50%", None))
        self.lineEdit_25.setText(_translate("Dialog", "1", None))
        self.lineEdit_26.setText(_translate("Dialog", "否", None))
        self.lineEdit_27.setText(_translate("Dialog", "2", None))
        self.lineEdit_28.setText(_translate("Dialog", "识别为滑坡，请及时处理情况！", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

